### ISSUE TITLE
[SOLVED] Remove node_modules 

### ISSUE THREAD

**Issue by dumblob** [CloudyChris/DarkSpear#1]
Hi Andrei, glad to see you're working on DarkSpear.

Anyway, could you please remove the node_modules directory? It's in `.gitignore`, but you anyway somehow managed to add it to the repository. Maybe it's because you're not using `git add --all` (the `--all` argument is always necessary unless you're doing something really crazy).

**Comment by CloudyChris** [comment]
I addressed the issue.. and now have a separate testing branch, which is only local and the main branch commit will not include the node_modules folder.

I am sorry for the slow development, however, I have upcoming exams and was featured in all sorts of projects at school... I plan on releasing an alfa, working version of the platform in September of this year.

**Comment by dumblob** [comment]
>I am sorry for the slow development, however, I have upcoming exams and was featured in all sorts of projects at school... I plan on releasing an alfa, working version of the platform in September of this year.

Well, then I hope you're improving and switching from messy Javascript stuff to proper languages like C and Go and when it comes to primarily interpreted languages, then Lisp and [Dao](https://github.com/daokoder/dao ). School time is the best opportunity to learn the true IT (i.e. what's behind the pile of manure like Javascript, HTML5, Java, and similar harmful stuff). The issue is, that universities nowadays doesn't require students to do the "hard" stuff and therefore it's a sole responsibility of the student to choose a broad range of subjects dealing with "the invisible, but hardest and most important part of IT".

By the way, you don't have to put `[SOLVED]` in front of the issue name - GitHub shows it clearly, that it's closed. If you really want to add some additional information, GitHub has tags for these purposes :wink:.
